-- MySQL Script generated by MySQL Workbench
-- vie 07 abr 2023 20:51:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Inmobiliaria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Inmobiliaria` ;

-- -----------------------------------------------------
-- Schema Inmobiliaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Inmobiliaria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
USE `Inmobiliaria` ;

-- -----------------------------------------------------
-- Table `Inmobiliaria`.`Propietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inmobiliaria`.`Propietario` (
  `idPropietario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idPropietario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inmobiliaria`.`Inmueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inmobiliaria`.`Inmueble` (
  `idInmueble` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(10) NULL,
  `coordenadas` VARCHAR(50) NULL,
  `precio` DECIMAL NULL,
  `ambientes` INT NULL,
  `uso` VARCHAR(45) NULL,
  `activo` TINYINT NULL,
  `idPropietario` INT NOT NULL,
  PRIMARY KEY (`idInmueble`),
  INDEX `fk_Inmueble_Propietario1_idx` (`idPropietario` ASC) VISIBLE,
  CONSTRAINT `fk_Inmueble_Propietario1`
    FOREIGN KEY (`idPropietario`)
    REFERENCES `Inmobiliaria`.`Propietario` (`idPropietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inmobiliaria`.`Inquilino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inmobiliaria`.`Inquilino` (
  `idInquilino` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `fecha_nacimiento` VARCHAR(45) NULL,
  PRIMARY KEY (`idInquilino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inmobiliaria`.`Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inmobiliaria`.`Contrato` (
  `idContrato` INT NOT NULL AUTO_INCREMENT,
  `idInquilino` INT NOT NULL,
  `idInmueble` INT NOT NULL,
  `fecha_inicio` DATETIME NULL,
  `fecha_fin` DATETIME NULL,
  PRIMARY KEY (`idContrato`),
  INDEX `fk_Contrato_Inquilino1_idx` (`idInquilino` ASC) VISIBLE,
  INDEX `fk_Contrato_Inmueble1_idx` (`idInmueble` ASC) VISIBLE,
  CONSTRAINT `fk_Contrato_Inquilino1`
    FOREIGN KEY (`idInquilino`)
    REFERENCES `Inmobiliaria`.`Inquilino` (`idInquilino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_Inmueble1`
    FOREIGN KEY (`idInmueble`)
    REFERENCES `Inmobiliaria`.`Inmueble` (`idInmueble`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inmobiliaria`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inmobiliaria`.`Pago` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `numero_de_pago` INT NULL,
  `importe` DECIMAL NULL,
  `idContrato` INT NOT NULL,
  PRIMARY KEY (`idPago`, `idContrato`),
  INDEX `fk_Pago_Contrato1_idx` (`idContrato` ASC) VISIBLE,
  CONSTRAINT `fk_Pago_Contrato1`
    FOREIGN KEY (`idContrato`)
    REFERENCES `Inmobiliaria`.`Contrato` (`idContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
